spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ISSBEL
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
wordpress:
  api-url: https://issbelensenanzachalaneria.wordpress.com/wp-json/wp/v2
