spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
wordpress:
  api-url: https://
